data:
  batch_size: 768
  num_workers: 8
  max_tokens: 77
  img_size: 224

dataset:
  gcc12m:
    path: /path/to/gcc12m_shards_dir
    prefix: gcc-conceptual-12m-{000000..001242}.tar
    full_path: /path/to/gcc12m_shards_dir/gcc-conceptual-12m-{000000..001242}.tar
    length: 12413374
    img_size: ${data.img_size}
  in1k:
    val_path: /path/to/imagenet/val/
    class_idx_path: /path/to/imagenet/imagenet_class_index.json
    img_size: ${data.img_size}

train:
  optimizer:
    name: adamw
    eps: 1.0e-6
    betas: [0.9, 0.999]

evaluate:
  eval_freq_steps: 2000

checkpoint:
  save_freq_steps: 1000

seed: 2024